[package]
name = "samael"
version = "0.0.9"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Alex Grinman <me@alexgr.in>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/njaremko/samael"
description = "A SAML2 library for Rust"
keywords = ["saml", "saml2", "xml", "sso"]
categories = ["authentication"]
build = "bindings.rs"

[lib]
# Disabling doctests because they cause nix build check phase to fail
doctest = false

[features]
default = ["openssl"]
xmlsec = ["libc", "lazy_static", "libxml"]
openssl = ["openssl", "openssl-sys", "openssl-probe"]
rustcrypto = ["rsa", "x509-parser"]

[build-dependencies]
pkg-config =  "^0.3.17"
bindgen    = "^0.60.1"

[dependencies]
base64 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
data-encoding = "2.2.0"
derive_builder = "0.11.2"
flate2 = "1.0"
lazy_static = {version = "^1.4.0", optional = true}
libc        = {version = "^0.2.66", optional = true}
libxml = { version = "0.3.0", optional = true}
quick-xml = { version = "0.23.0", features = [ "serialize" ] }
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
snafu = "0.7"
url = "2.1.1"
uuid = { version = ">=0.8.0, <2.0.0", features = [ "v4" ] }

# openssl
openssl = { version = "0.10", optional = true }
openssl-sys = { version = "0.9", optional = true }
openssl-probe = { version = "0.1.2", optional = true }

# rustcrypto
rsa = { version = "0.5.0", optional = true }
x509-parser = { version = "0.13.0", optional = true }
